{ config, pkgs, harpoonWasm, zjstatusWasm, ... }:

let
  # Started as Zellij's own autogenerated config (there was no config.kdl
  # here before), with the zj-agent-harpoon Alt+a wiring added — see
  # zellij/agent-config.kdl's own header comment. Deployed here so it can't
  # drift out of sync with the plugin again the way it did across the
  # sidebar -> agent-harpoon rename (old MessagePlugin bindings kept
  # pointing at the retired sidebar wasm for a full rebuild cycle since
  # nothing previously managed this file declaratively).
  agentZellijConfig = builtins.path {
    path = ../zellij/agent-config.kdl;
    name = "agent-zellij-config";
  };

  # richard's config mirrors his local Mac setup verbatim (same file,
  # copied byte-for-byte) — its plugin paths use `~`, which resolves fine
  # per-user, so no per-machine path rewriting needed.
  richardZellijConfig = builtins.path {
    path = ../zellij/richard-config.kdl;
    name = "richard-zellij-config";
  };
  richardZellijLayout = builtins.path {
    path = ../zellij/richard-layout-default.kdl;
    name = "richard-zellij-layout";
  };
in
{
  systemd.tmpfiles.rules = [
    # Explicit owned parent dirs, not left to L+'s auto-mkdir: a root-owned
    # intermediate dir under a user's home makes systemd-tmpfiles skip
    # later entries with "unsafe path transition" (agent-env.nix hit this
    # already for the plugins dir).
    "d /home/agent/.config/zellij 0755 agent users - -"
    "L+ /home/agent/.config/zellij/config.kdl - - - - ${agentZellijConfig}"

    "d /home/richard/.config 0755 richard users - -"
    "d /home/richard/.config/zellij 0755 richard users - -"
    "d /home/richard/.config/zellij/plugins 0755 richard users - -"
    "d /home/richard/.config/zellij/layouts 0755 richard users - -"
    "L+ /home/richard/.config/zellij/config.kdl - - - - ${richardZellijConfig}"
    "L+ /home/richard/.config/zellij/layouts/default.kdl - - - - ${richardZellijLayout}"
    "L+ /home/richard/.config/zellij/plugins/harpoon.wasm - - - - ${harpoonWasm}"
    "L+ /home/richard/.config/zellij/plugins/zjstatus.wasm - - - - ${zjstatusWasm}"
    # richard's config also has the Alt+a agent-harpoon bind (copied
    # verbatim from the Mac config) — needs the same two plugin wasms
    # agent-env.nix already deploys for `agent`.
    "L+ /home/richard/.config/zellij/plugins/zj-agent-state-watcher.wasm - - - - ${config.programs.zj-agent-harpoon.package}/lib/zellij/zj-agent-state-watcher.wasm"
    "L+ /home/richard/.config/zellij/plugins/zj-agent-state-harpoon.wasm - - - - ${config.programs.zj-agent-harpoon.package}/lib/zellij/zj-agent-state-harpoon.wasm"
  ];
}
