{ config, pkgs, ... }:

let
  # Started as Zellij's own autogenerated config (there was no config.kdl
  # here before), with the zj-agent-harpoon Alt+a wiring added — see
  # zellij/config.kdl's own header comment. Deployed here so it can't drift
  # out of sync with the plugin again the way it did across the
  # sidebar -> agent-harpoon rename (old MessagePlugin bindings kept
  # pointing at the retired sidebar wasm for a full rebuild cycle since
  # nothing previously managed this file declaratively).
  agentZellijConfig = builtins.path {
    path = ../zellij/config.kdl;
    name = "agent-zellij-config";
  };
in
{
  systemd.tmpfiles.rules = [
    # Explicit agent-owned parent dir, not left to L+'s auto-mkdir: a
    # root-owned intermediate dir under agent's home makes systemd-tmpfiles
    # skip later entries with "unsafe path transition" (agent-env.nix hit
    # this already for the plugins dir).
    "d /home/agent/.config/zellij 0755 agent users - -"
    "L+ /home/agent/.config/zellij/config.kdl - - - - ${agentZellijConfig}"
  ];
}
