import express from 'express';
import {randomUUID} from 'node:crypto';
import {writeFileSync} from 'node:fs';
import {createDb,companies,agents,companyMemberships} from '@paperclipai/db';
import {fileURLToPath} from 'node:url';
const {agentRoutes}=await import(new URL('dist/routes/agents.js',process.env.PAPERCLIP_TEST_SERVER_URL));
const db=createDb('postgresql:///postgres');
const companyId=randomUUID(),id=randomUUID(),prefix='UIT'+Date.now();
const [company]=await db.insert(companies).values({id:companyId,name:'Isolated permission browser check',issuePrefix:prefix}).returning();
await db.insert(agents).values({id,companyId,name:'Permission fixture',permissions:{canAssignTasks:false,canCreateAgents:false,canCreateSkills:false},runtimeConfig:{heartbeat:{enabled:false}}});
await db.insert(companyMemberships).values({companyId,principalType:'agent',principalId:id,membershipRole:'member',status:'active'});
const app=express();app.use(express.json());
app.use((req,res,next)=>{req.actor={type:'board',source:'local_implicit',isInstanceAdmin:true,companyIds:[companyId]};next();});
let failSave=false;
app.post('/test/fail-save',(req,res)=>{failSave=!!req.body.enabled;res.json({enabled:failSave});});
app.patch('/api/agents/:id/permissions',(req,res,next)=>failSave?res.status(403).json({error:'Isolated permission save rejection'}):next());
app.get('/api/health',(req,res)=>res.json({status:'ok',deploymentMode:'local_trusted',deploymentExposure:'private',authReady:true,bootstrapStatus:'ready'}));
app.get('/api/cli-auth/me',(req,res)=>res.json({user:{id:'browser-fixture',name:'Isolated reviewer',email:'fixture@example.invalid'},userId:'browser-fixture',isInstanceAdmin:true,companyIds:[companyId],memberships:[],source:'local_implicit',keyId:null}));
app.get('/api/auth/get-session',(req,res)=>res.json(null));
app.get('/api/companies',(req,res)=>res.json([company]));
app.get('/api/companies/:id',(req,res)=>res.json(company));
app.use('/api',agentRoutes(db));
app.get('/api/companies/:id/projects',(req,res)=>res.json([]));
app.get('/api/companies/:id/approvals',(req,res)=>res.json([]));
app.get('/api/companies/:id/issues',(req,res)=>res.json([]));
app.use('/api',(req,res)=>res.status(404).json({error:'Endpoint outside isolated fixture: '+req.url}));
const ui=fileURLToPath(new URL('ui-dist/',process.env.PAPERCLIP_TEST_SERVER_URL));
app.use(express.static(ui));app.get('/{*path}',(req,res)=>res.sendFile(ui+'/index.html'));
app.use((err,req,res,next)=>res.status(err.status||500).json({error:err.message}));
const server=app.listen(0,'127.0.0.1',()=>{const base=`http://127.0.0.1:${server.address().port}`;writeFileSync((process.env.PAPERCLIP_TEST_SCRATCH || process.env.PAPERCLIP_RUN_SCRATCH_DIR)+'/repair/browser-fixture.json',JSON.stringify({base,url:`${base}/${prefix}/agents/${id}/permissions`,id,companyId}));console.log('Isolated browser fixture ready');});
