/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ColumnColumnIdRouteImport } from './routes/column.$columnId'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ColumnColumnIdJobJobIdRouteImport } from './routes/column.$columnId.job.$jobId'
import { Route as ColumnColumnIdJobNewRouteImport } from './routes/column.$columnId.job.new'
import { Route as ColumnColumnIdJobJobIdTaskTaskIdRouteImport } from './routes/column.$columnId.job.$jobId.task.$taskId'
import { Route as ColumnColumnIdJobJobIdTaskNewRouteImport } from './routes/column.$columnId.job.$jobId.task.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnColumnIdRoute = ColumnColumnIdRouteImport.update({
  id: '/column/$columnId',
  path: '/column/$columnId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnColumnIdJobJobIdRoute = ColumnColumnIdJobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => ColumnColumnIdRoute,
} as any)
const ColumnColumnIdJobNewRoute = ColumnColumnIdJobNewRouteImport.update({
  id: '/job/new',
  path: '/job/new',
  getParentRoute: () => ColumnColumnIdRoute,
} as any)
const ColumnColumnIdJobJobIdTaskTaskIdRoute =
  ColumnColumnIdJobJobIdTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => ColumnColumnIdJobJobIdRoute,
  } as any)
const ColumnColumnIdJobJobIdTaskNewRoute =
  ColumnColumnIdJobJobIdTaskNewRouteImport.update({
    id: '/task/new',
    path: '/task/new',
    getParentRoute: () => ColumnColumnIdJobJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/api/$': typeof ApiSplatRoute
  '/column/$columnId': typeof ColumnColumnIdRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/column/$columnId/job/$jobId': typeof ColumnColumnIdJobJobIdRouteWithChildren
  '/column/$columnId/job/new': typeof ColumnColumnIdJobNewRoute
  '/column/$columnId/job/$jobId/task/$taskId': typeof ColumnColumnIdJobJobIdTaskTaskIdRoute
  '/column/$columnId/job/$jobId/task/new': typeof ColumnColumnIdJobJobIdTaskNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/api/$': typeof ApiSplatRoute
  '/column/$columnId': typeof ColumnColumnIdRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/column/$columnId/job/$jobId': typeof ColumnColumnIdJobJobIdRouteWithChildren
  '/column/$columnId/job/new': typeof ColumnColumnIdJobNewRoute
  '/column/$columnId/job/$jobId/task/$taskId': typeof ColumnColumnIdJobJobIdTaskTaskIdRoute
  '/column/$columnId/job/$jobId/task/new': typeof ColumnColumnIdJobJobIdTaskNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/api/$': typeof ApiSplatRoute
  '/column/$columnId': typeof ColumnColumnIdRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/column/$columnId/job/$jobId': typeof ColumnColumnIdJobJobIdRouteWithChildren
  '/column/$columnId/job/new': typeof ColumnColumnIdJobNewRoute
  '/column/$columnId/job/$jobId/task/$taskId': typeof ColumnColumnIdJobJobIdTaskTaskIdRoute
  '/column/$columnId/job/$jobId/task/new': typeof ColumnColumnIdJobJobIdTaskNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/api/$'
    | '/column/$columnId'
    | '/api/rpc/$'
    | '/column/$columnId/job/$jobId'
    | '/column/$columnId/job/new'
    | '/column/$columnId/job/$jobId/task/$taskId'
    | '/column/$columnId/job/$jobId/task/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/api/$'
    | '/column/$columnId'
    | '/api/rpc/$'
    | '/column/$columnId/job/$jobId'
    | '/column/$columnId/job/new'
    | '/column/$columnId/job/$jobId/task/$taskId'
    | '/column/$columnId/job/$jobId/task/new'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/api/$'
    | '/column/$columnId'
    | '/api/rpc/$'
    | '/column/$columnId/job/$jobId'
    | '/column/$columnId/job/new'
    | '/column/$columnId/job/$jobId/task/$taskId'
    | '/column/$columnId/job/$jobId/task/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ColumnColumnIdRoute: typeof ColumnColumnIdRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column/$columnId': {
      id: '/column/$columnId'
      path: '/column/$columnId'
      fullPath: '/column/$columnId'
      preLoaderRoute: typeof ColumnColumnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column/$columnId/job/$jobId': {
      id: '/column/$columnId/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/column/$columnId/job/$jobId'
      preLoaderRoute: typeof ColumnColumnIdJobJobIdRouteImport
      parentRoute: typeof ColumnColumnIdRoute
    }
    '/column/$columnId/job/new': {
      id: '/column/$columnId/job/new'
      path: '/job/new'
      fullPath: '/column/$columnId/job/new'
      preLoaderRoute: typeof ColumnColumnIdJobNewRouteImport
      parentRoute: typeof ColumnColumnIdRoute
    }
    '/column/$columnId/job/$jobId/task/$taskId': {
      id: '/column/$columnId/job/$jobId/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/column/$columnId/job/$jobId/task/$taskId'
      preLoaderRoute: typeof ColumnColumnIdJobJobIdTaskTaskIdRouteImport
      parentRoute: typeof ColumnColumnIdJobJobIdRoute
    }
    '/column/$columnId/job/$jobId/task/new': {
      id: '/column/$columnId/job/$jobId/task/new'
      path: '/task/new'
      fullPath: '/column/$columnId/job/$jobId/task/new'
      preLoaderRoute: typeof ColumnColumnIdJobJobIdTaskNewRouteImport
      parentRoute: typeof ColumnColumnIdJobJobIdRoute
    }
  }
}

interface ColumnColumnIdJobJobIdRouteChildren {
  ColumnColumnIdJobJobIdTaskTaskIdRoute: typeof ColumnColumnIdJobJobIdTaskTaskIdRoute
  ColumnColumnIdJobJobIdTaskNewRoute: typeof ColumnColumnIdJobJobIdTaskNewRoute
}

const ColumnColumnIdJobJobIdRouteChildren: ColumnColumnIdJobJobIdRouteChildren =
  {
    ColumnColumnIdJobJobIdTaskTaskIdRoute:
      ColumnColumnIdJobJobIdTaskTaskIdRoute,
    ColumnColumnIdJobJobIdTaskNewRoute: ColumnColumnIdJobJobIdTaskNewRoute,
  }

const ColumnColumnIdJobJobIdRouteWithChildren =
  ColumnColumnIdJobJobIdRoute._addFileChildren(
    ColumnColumnIdJobJobIdRouteChildren,
  )

interface ColumnColumnIdRouteChildren {
  ColumnColumnIdJobJobIdRoute: typeof ColumnColumnIdJobJobIdRouteWithChildren
  ColumnColumnIdJobNewRoute: typeof ColumnColumnIdJobNewRoute
}

const ColumnColumnIdRouteChildren: ColumnColumnIdRouteChildren = {
  ColumnColumnIdJobJobIdRoute: ColumnColumnIdJobJobIdRouteWithChildren,
  ColumnColumnIdJobNewRoute: ColumnColumnIdJobNewRoute,
}

const ColumnColumnIdRouteWithChildren = ColumnColumnIdRoute._addFileChildren(
  ColumnColumnIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  ApiSplatRoute: ApiSplatRoute,
  ColumnColumnIdRoute: ColumnColumnIdRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
